### ISSUE TITLE
SeCaPr - Sequence Capture Processor

### ISSUE THREAD

**Issue by RominaSSBatista** [The-Bioinformatics-Group/Albiorix#101]
It seems the updates @tobiashofmann88 made is not available yet. Can we have it, @mtop ? [SeqCaPr](https://github.com/AntonelliLab/seqcap_processor/blob/master/documentation.ipynb). I would like to know if it is straightforward activate the environment by `source activate` cmmd line on Albiorix? thanks!!!

**Comment by mtop** [comment]
Hi @RominaSSBatista The latest version of Tobis code is now available under Anaconda v4.4.0 `module load Anaconda2/v4.4.0`.

**Comment by RominaSSBatista** [comment]
Hi @mtop I am trying to use it by typing:

`$ module load Anaconda2/v4.4.0`
`$ secapr --help`

- I get the following msg: 
`Traceback (most recent call last):`
 ` File "/usr/local/packages/anaconda2-4.4.0/bin/secapr", line 6, in <module>`
  `  from pkg_resources import load_entry_point`
 ` File "/usr/local/packages/anaconda2/lib/python2.7/site-packages/pkg_resources.py", line 2850, in <module>`
    `working_set.require(__requires__)`
`  File "/usr/local/packages/anaconda2/lib/python2.7/site-packages/pkg_resources.py", line 696, in require`
`    needed = self.resolve(parse_requirements(requirements))`
`  File "/usr/local/packages/anaconda2/lib/python2.7/site-packages/pkg_resources.py", line 594, in resolve`
  `  raise DistributionNotFound(req)`
`pkg_resources.DistributionNotFound: secapr==1.0.2`

- I am wondering if you did this command?
 `conda create -n secapr_env -c bioconda secapr` 

- Because I am not been able to `source activate secapr_env` as Tobi suggests in his code. 

thanks! 👍

**Comment by tandermann** [comment]
in case you want to install secapr locally on your Albiorix home directory you can also just type the following:
`sh /usr/local/ubin/envs/install_and_activate_secapr.sh`

Then you can activate the environment like this:

`source ./miniconda/bin/activate secapr`

Best,
Tobi

**Comment by mtop** [comment]
I've made a global installation now. `source activate secapr_env`works now.

**Comment by tandermann** [comment]
thats great news, then I don't have to have all students install the software locally! Thanks Mats!

**Comment by RominaSSBatista** [comment]
I was wondering to do it in my home directory after @mtop ask to clean it because it is getting full... But I just made it... I will remove and use the global one that mats installed. Thanks tobi & Mats!!!!

**Comment by tandermann** [comment]
also be aware that you'll have to reactivate the secapr_env if you qlogin or run an sge script on high_mem or node0 (simply add `source activate secapr_env` to the sge script)

**Comment by RominaSSBatista** [comment]
ok! thanks tobi!

**Comment by paolaferreira** [comment]
Hello everyone,
I found this error when I was trying to do the R script
(secapr_env) [paola@albiorix trimming_default]$ Rscript fastqc_visualization.r -i /nobackup/data14/paola/barna_sequences/trimming_default/fastq-results -o /nobackup/data14/paola/barna_sequences/trimming_default/fastq-results/fastq-result.pdf
Loading required package: optparse
Loading required package: tidyverse
Warning in install.packages("tidyverse", repos = "http://cran.us.r-project.org") :
  'lib = "/state/partition1/home/local/packages/R-3.1.3/library"' is not writable
Error in install.packages("tidyverse", repos = "http://cran.us.r-project.org") :
  unable to install packages
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'tidyverse'
Execution halted

How can I solve it?

Thanks..
