### ISSUE TITLE
Rscript

### ISSUE THREAD

**Issue by paolaferreira** [The-Bioinformatics-Group/Albiorix#102]
Hello everyone,
I found this error when I was trying to do the R script
(secapr_env) [paola@albiorix trimming_default]$ Rscript fastqc_visualization.r -i /nobackup/data14/paola/barna_sequences/trimming_default/fastq-results -o /nobackup/data14/paola/barna_sequences/trimming_default/fastq-results/fastq-result.pdf
Loading required package: optparse
Loading required package: tidyverse
Warning in install.packages("tidyverse", repos = "http://cran.us.r-project.org") :
'lib = "/state/partition1/home/local/packages/R-3.1.3/library"' is not writable
Error in install.packages("tidyverse", repos = "http://cran.us.r-project.org") :
unable to install packages
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
there is no package called 'tidyverse'
Execution halted

How can I fix it?

Thanks..

**Comment by mtop** [comment]
Hi @paolaferreira 
I have installed `tidyverse` for version 3.2.3 of R. Hope that is fine? Uou can access that version by furst running the command `module load R/v.3.2.3`. There might be other dependencies missing so give it a try and let me know if it doesn't work.

Cheers
#Mats

**Comment by paolaferreira** [comment]
Now, the script is requesting another package

[paola@albiorix trimming_default]$ Rscript fastqc_visualization.r -i /nobackup/data14/paola/barna_sequences/trimming_default/ -o /nobackup/data14/paola/barna_sequences/trimming_default/fastq-results/summary_all_samples_default.pdf
Loading required package: optparse
Warning in install.packages("optparse", repos = "http://cran.us.r-project.org") :
  'lib = "/state/partition1/home/local/packages/R-3.2.3/library"' is not writable
Error in install.packages("optparse", repos = "http://cran.us.r-project.org") :
  unable to install packages
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'optparse'
Execution halted

**Comment by mtop** [comment]
OK, installed that now. Try again.
#Mats

**Comment by paolaferreira** [comment]
[paola@albiorix trimming_default]$ Rscript fastqc_visualization.r -i /nobackup/data14/paola/barna_sequences/trimming_default/ -o /nobackup/data14/paola/barna_sequences/trimming_default/fastq-results/summary_all_samples_default.pdf
Loading required package: optparse
Loading required package: tidyverse
Warning: program compiled against libxml 209 using older 207
Loading tidyverse: ggplot2
Loading tidyverse: tibble
Loading tidyverse: tidyr
Loading tidyverse: readr
Loading tidyverse: purrr
Loading tidyverse: dplyr
Conflicts with tidy packages ---------------------------------------------------
filter(): dplyr, stats
lag():    dplyr, stats
Warning message:
In .doLoadActions(where, attach) :
  trying to execute load actions without 'methods' package
Error in overscope_eval_next(overscope, expr) :
  object 'sample_id' not found
Calls: %>% ... map -> lapply -> FUN -> overscope_eval_next -> .Call
Execution halted

**Comment by mtop** [comment]
Hi again
Not sure what causes this, but found something similar at https://github.com/STAT545-UBC/Discussion/issues/331. I think you should contact the developer of this package to see if you can get some help.

Alternatively you can try the version installed under version 3.3.2 /`module load R/v.3.3.2`.

Cheers
#Mats
