### ISSUE TITLE
I can't log in

### ISSUE THREAD

**Issue by fernandafreitas** [The-Bioinformatics-Group/Albiorix#103]
Hi @mtop I believe that I can't log in  Albiorix because my user was deleted.
Paola has checked on home and data14 and she couldn't recognize any Fernanda user.
Could you create a new one for me?

Thanks

**Comment by mtop** [comment]
Hi @fernandafreitas 
Sure, not problem. Please contact me on Slack and we'll sort this out.
Cheers
#Mats
