### ISSUE TITLE
Install ExaBayes

### ISSUE THREAD

**Issue by RominaSSBatista** [The-Bioinformatics-Group/Albiorix#106]
Hi @mtop, could we have [ExaBayes](https://sco.h-its.org/exelixis/web/software/exabayes/) installed? Thanks.

**Comment by mtop** [comment]
Hi Romina

After giving up a couple of times I have now managed to install ExaBayes. Run `module load Exabayes/v1.5` to access it. I had to disable `avx` in order for the code to compile, and this means that the program will not run as fast as it otherwise would have.

Cheers
Mats
