### ISSUE TITLE
User forum

### ISSUE THREAD

**Issue by mtop** [The-Bioinformatics-Group/Albiorix#17]
We have discussed if the google group can be used as a forum for users to post questions and discuss bugs and solutions to HPC problems. Jose will look into this.

**Comment by jlblancopastor** [comment]
Ok, I'will look into this. I have created my Github account

**Comment by jlblancopastor** [comment]
I came up with a solution that I feel will satisfy everyone.

The first step would be to embed the google group in the Albiorix webpage. As we mentioned in the meeting the webpage should serve as the core of Albiorix, the first place to go for everything related to the cluster.

To embeed the google group in the Albiorix webpage check this: https://support.google.com/groups/answer/1191206?hl=en

The google group should then serve as the forum to post questions and discuss bugs and issues. But as we mentioned we don't want that all replies to be sent to every member of the google group. Therefore I would limit the responses given in the forum so the reply only gets to the person who sent the original message. See how to do this here:

https://support.google.com/groups/answer/4600446

What do you think?

JLBP

**Comment by Patrulk** [comment]
To me this sounds like a great solution, I Think there are some definite upsides to having one single page for all albiorix needs.

**Comment by jlblancopastor** [comment]
If I have been assigned to do that I will need administrative access to the albiorix webpage, isn't it?
I have 0 experience with webpage administration, but I could give it a try...

**Comment by mtop** [comment]
Hi guys

Thanks @jlblancopastor. I have implemented your suggestions on the Albiorix web site (http://albiorix.bioenv.gu.se/). The layout of the page is not as it should yet, but at least the function is there. Also, replies to messages are directed to the person posting the question.

Let's try this for a while and see how it goes.

**Comment by mtop** [comment]
If the answer to a question on the google group is only directed to the person asking the question, how does it end up in the feed on the google list?

**Comment by jlblancopastor** [comment]
I think it is only directed to the person asking the question via e-mail. But it is registered in the forum, so anyone can access the answer.

We can make a test question to check how it works.

**Comment by mtop** [comment]
Yes, please post a question to the list to test the functionality. It would be best if it is a "real" question related to Albiorix.

**Comment by jlblancopastor** [comment]
I have posted a question in the Forum. The response should only arrive to me if it is answered trough the forum as I understand. I don't know what will happen if it is replied via e-mail to albiorix@googlegroups.com. But I guess it will be sent to everyone. We should encourage the people to ask and respond via the forum to keep the inboxes of the people free of unwanted emails.

JL

**Comment by mtop** [comment]
A user forum is now available at https://albiorix.slack.com. Anyone with an @gu.se address can join without invitation. Anyone else can send me a message.
