### ISSUE TITLE
User accounts

### ISSUE THREAD

**Issue by mtop** [The-Bioinformatics-Group/Albiorix#18]
We need to list all current users and assign them to departments, research groups etc.

**Comment by Patrulk** [comment]
[user_accounts_combined_lists.xlsx](https://github.com/The-Bioinformatics-Group/albiorix/files/38861/user_accounts_combined_lists.xlsx)

Hi, I put together a spreadsheet with the accounts on the cluster and filled in the affiliations I know but there are many people left on the list, If you could fill in the ones you know I can go through the last missing ones afterwards.

**Comment by mtop** [comment]
@Patrulk did this some some ago.
