### ISSUE TITLE
Cpan, perl & co

### ISSUE THREAD

**Issue by hettling** [The-Bioinformatics-Group/Albiorix#22]
Hi @mtop,
would it be possible to install cpan and cpanm (cpan minus) for installing perl modules?
Thanks,
Hannes

**Comment by mtop** [comment]
Hi @hettling. Sure. @n-equals-one (our Perl guru :-)) will handle the installation of Perl in version 4.0 of Albiorix. I'll forward this issue to him.

**Comment by mtop** [comment]
We have cpan installed for v5.14.4 and v5.22.1 so I guess this issue can ve closed now.
