### ISSUE TITLE
Perl Locale problem

### ISSUE THREAD

**Issue by mtop** [The-Bioinformatics-Group/Albiorix#23]
Several members of the group sees this eror message when running Perl code on remode machines:

perl: warning: Falling back to the standard locale ("C").
Added "Human/hs_alt_CHM1_1.1_chrX.fa" to library (CustomDB)
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
    LANGUAGE = "en_US:en",
    LC_ALL = (unset),
    LC_PAPER = "sv_SE.UTF-8",
    LC_ADDRESS = "sv_SE.UTF-8",
    LC_MONETARY = "sv_SE.UTF-8",
    LC_NUMERIC = "sv_SE.UTF-8",
    LC_TELEPHONE = "sv_SE.UTF-8",
    LC_IDENTIFICATION = "sv_SE.UTF-8",
    LC_MEASUREMENT = "sv_SE.UTF-8",
    LC_TIME = "sv_SE.UTF-8",
    LC_NAME = "sv_SE.UTF-8",
    LANG = "en_US.UTF-8"
    are supported and installed on your system.

Does anyone know how to fix this and could write a tutorial for it?

**Comment by hettling** [comment]
We had a similar issue on supersmart virtual machines, `export LC_ALL=en_US.UTF-8` fixed it (see https://github.com/naturalis/supersmart/issues/43)
