### ISSUE TITLE
Install Poppr

### ISSUE THREAD

**Issue by crustaceana** [The-Bioinformatics-Group/Albiorix#39]

**Comment by mtop** [comment]
Hi @crustaceana!

Do you have a link where I can download this program? 

Thanks 
#Mats

**Comment by crustaceana** [comment]
Github (https://github.com/grunwaldlab/poppr):
You can also install poppr via github with the following commands (make sure the devtools package is installed):

install.packages("devtools")
library(devtools)

# For the most recent version:

install_github("grunwaldlab/poppr")

All info about the package is here: 

http://grunwaldlab.cgrb.oregonstate.edu/primer-population-genetic-analyses-r/installation

**Comment by mtop** [comment]
Thanks!
The library has been installed for version 3.1.3 of R. This version is available using "module load R/v.3.1.3"
