### ISSUE TITLE
install ExaML: Exascale Maximum Likelihood

### ISSUE THREAD

**Issue by RominaSSBatista** [The-Bioinformatics-Group/Albiorix#45]
"This code implements the popular RAxML search algorithm for maximum likelihood based inference of phylogenetic trees. It uses a radically new MPI parallelization approach that yields improved parallel efficiency, in particular on partitioned multi-gene or whole-genome datasets.
It is up to 4 times faster than RAxML-Light [1]."

**Comment by mtop** [comment]
module load ExaML/v3.0.17
