### ISSUE TITLE
install treemix

### ISSUE THREAD

**Issue by RominaSSBatista** [The-Bioinformatics-Group/Albiorix#49]
https://bitbucket.org/nygcresearch/treemix/downloads.
TreeMix is a method for inferring the patterns of population splits and mixtures in the history of a set of populations. In the underlying model, the modern-day populations in a species are related to a common ancestor via a graph of ancestral populations.

**Comment by jlblancopastor** [comment]
Hi Romina
I have already installed TreeMix in usr/local/ubin

cheers
JL

**Comment by RominaSSBatista** [comment]
Awesome!!! Thank you Jose!

**Comment by mtop** [comment]
Available using "module avail Treemix/v.1.12".
