### ISSUE TITLE
Install AGeS

### ISSUE THREAD

**Issue by oskarvid** [The-Bioinformatics-Group/Albiorix#54]
http://bhsai.org/downloads/ages.tar.gz

**Comment by mtop** [comment]
Probably need zlib 86_64 to compile some of the Perl dependencies.

**Comment by oskarvid** [comment]
Since I won't be working with anything on Albiorix anymore it's up to you
how much effort you want to put into this.

/Oskar

**Comment by mtop** [comment]
module load AGeS/vX.X
