### ISSUE TITLE
install trinityrnaseq_r2013-02-25  

### ISSUE THREAD

**Issue by RominaSSBatista** [The-Bioinformatics-Group/Albiorix#63]
:top: :top: :top: 

Hi @mtop this [trinity](https://www.dropbox.com/s/aq2b6xg61z3hhdp/trinityrnaseq_r2013-02-25.tgz?dl=0)  version, it seems to keep longer contigs.

:exclamation:  **Personal Notes**: some changes needs to be done on _assemblo_trinity.py_ before use this version. I need to figure out this.

**Comment by mtop** [comment]
Hi @RominaSSBatista 
Are you sure you want this old version of Trinity? The latest version (/usr/local/bin/trinityrnaseq-2.2.0/Trinity) is installed and working now.

**Comment by RominaSSBatista** [comment]
Hummmm :thought_balloon:

I will agree with you @mtop. Let me try it (2.2.0) first. 

Thank you!! :+1:

**Comment by mtop** [comment]
OK, I'll install the latest version then.
