### ISSUE TITLE
intall Phyluce v1.5

### ISSUE THREAD

**Issue by RominaSSBatista** [The-Bioinformatics-Group/Albiorix#64]
**Phyluce** [v1.5](http://phyluce.readthedocs.io/en/latest/installation.html) (April 2015)

:new:
- added configuration file system for binary dependencies
- moved many older scripts to attic
- prepended “phyluce” and purpose of program to all programs
- cleaned header and argparse entries
- added tutorial

**Comment by mtop** [comment]
Phyluce v.X.X has been installed using annaconda v.2.5.0. The software is available as a module called "Phyluce/v.X.X".
