### ISSUE TITLE
Install seqcap_processor

### ISSUE THREAD

**Issue by RominaSSBatista** [The-Bioinformatics-Group/Albiorix#83]
:white_check_mark: [seqcap_processor](https://github.com/AntonelliLab/seqcap_processor) automated workflow for processing and analyzing Illumina read data

**Comment by mtop** [comment]
Hi @RominaSSBatista. Tobis package has now been installed and is available if you first run the command "module load seqcap_processor/vX.X". Also, remember to include that command in any SGE scripts you write.

**Comment by RominaSSBatista** [comment]
:+1: Thanks a lot @mtop!

**Comment by mtop** [comment]
module load seqcap_processor/vX.X
