### ISSUE TITLE
BEAS2/v2.4.2

### ISSUE THREAD

**Issue by RominaSSBatista** [The-Bioinformatics-Group/Albiorix#85]
Hi @mtop,  
I have tried to use **module load Beast2/v2.4.2** because I would like to use the latest version of [BEAST2](http://beast2.org/2016/06/22/what-is-new-in-v2-4-2/), but I got an ERROR :warning: saying : 

**Beast2(7):ERROR:105: Unable to locate a modulefile for 'Beast2/v2.4.2'**.

:sos: Should I open an issue requesting to install [Beast2/v2.4.2](http://beast2.org/)?

**Comment by mtop** [comment]
Hi @RominaSSBatista 
This version of Beast2 is not yet installed on Albiorix ("module avail" will show you the installed programs) but I will install it when I'm back from vacation. 

Cheers
Mats

**Comment by mtop** [comment]
OK, back from vacation now... Version 2.4.3 has been installed.

Enjoy
