### ISSUE TITLE
Install Trinity Old version

### ISSUE THREAD

**Issue by RominaSSBatista** [The-Bioinformatics-Group/Albiorix#88]
Link to download  [Trinity](https://www.dropbox.com/s/aq2b6xg61z3hhdp/trinityrnaseq_r2013-02-25.tgz?dl=0)
Release 2013-02-25

**Comment by mtop** [comment]
Hi @RominaSSBatista 
The requested version of Trinity is now installed. Access it using 'module load Trinity/r2013-02-25'.

This installation is using a later version of the rsem package (version 1.2.15 rather then 1.2.3) but I don't think that will be any problem for your analysis.

Also, version 'r20140717' of trinity has been installed and is available using the command 'Trinity/r20140717', in case you want to try another legacy version.

**Comment by mtop** [comment]
Accidentally closed this issue.

**Comment by RominaSSBatista** [comment]
Great, thanks @mtop ! I will have a look.
