### ISSUE TITLE
Install Cloudforest

### ISSUE THREAD

**Issue by RominaSSBatista** [The-Bioinformatics-Group/Albiorix#91]
Install [CloudForest](https://github.com/ngcrawford/CloudForest)

**Comment by mtop** [comment]
Hi @RominaSSBatista I have not been able to find that much information about this program, but it seem like it requires Hadoop. Do you know if that is correct? If so, we can't run it on Albiorix.

**Comment by RominaSSBatista** [comment]
Hi @mtop, thanks for your reply. I was trying to use CloudForest to generate genetrees. I managed to adjust a script for RAxML to run genetrees. It is absolutely OK if we do not have CloudForest on Albiorix, for now. Thanks!
