### ISSUE TITLE
Install BayPass

### ISSUE THREAD

**Issue by jlblancopastor** [The-Bioinformatics-Group/Albiorix#92]
http://www1.montpellier.inra.fr/CBGP/software/baypass/

**Comment by mtop** [comment]
Hi @jlblancopastor 

I have installed 'baypass' in '/usr/local/packages/baypass_2.1' and you can access it using the command "module load baypass/vX.X". Not sure how this program works but please have a look at it an get back to me if you need assistance.

Cheers
#Mats
