### ISSUE TITLE
Install R-package "rbrothers"

### ISSUE THREAD

**Issue by Patrulk** [The-Bioinformatics-Group/Albiorix#93]
Tried installing rbrothers as a local library but it is not in the CRAN archive and requires the packages "git2r" and "devtools" for installation, which it seems I cannot install either. 
Any ideas on how to solve this or can someone make a general installation of the package on the cluster?

**Comment by mtop** [comment]
Hi @Patrulk. I can install the package globally. Which version of R are you using?

**Comment by Patrulk** [comment]
Hi @mtop, Great, I am using R v.3.2.3. Thanks!

**Comment by mtop** [comment]
Hi @Patrulk. It was quite difficult to install this package under version 3.2.3 of R, as some of the dependencies where not available. I have therefore installed the latest version of R and then installed "rbrothers" there instead. This version is available using the command "module load R/v.3.3.2". Hope this is OK.

**Comment by Patrulk** [comment]
Hi @mtop. No problem at all, that works great. Thank you for fixing this and putting in the extra effort with the installation!

**Comment by Patrulk** [comment]
Hi @mtop. I had some problems trying to run the rbrothers package, do I need to use any specific node?

On the main node there seems to be missing a library and return the message:
"/usr/local/packages/R-3.3.2/lib64/R/bin/exec/R: error while loading shared libraries: liblzma.so.5: cannot open shared object file: No such file or directory"

On the other nodes it fails to load the rJava library.

Is there some other action I need to take Before running it?

**Comment by mtop** [comment]
Hi @Patrulk Has this problem been resolved?
