### ISSUE TITLE
Install PartitionFinder2

### ISSUE THREAD

**Issue by RominaSSBatista** [The-Bioinformatics-Group/Albiorix#95]
[PartitionFinder2](https://github.com/brettc/partitionfinder), for more [info](http://www.robertlanfear.com/partitionfinder/tutorial/)

**Comment by mtop** [comment]
Installed but untested now. Available by running the command `module load Partitionfinder2/v2.1.1`, and the neither of the commands `PartitionFinder.py`, `PartitionFinderProtein.py` or `PartitionFinderMorphology.py`.

**Comment by RominaSSBatista** [comment]
thanks @mtop !
