### ISSUE TITLE
Install Python module Bio

### ISSUE THREAD

**Issue by jlblancopastor** [The-Bioinformatics-Group/Albiorix#96]
http://biopython.org/

**Comment by jlblancopastor** [comment]
http://biopython.org/

**Comment by mtop** [comment]
Hi @jlblancopastor. Which version of python are you using? The biopython module is installed in the default python installation
```
[mtop@albiorix ~]$ which python
/usr/local/packages/anaconda2/bin/python
```

**Comment by jlblancopastor** [comment]
HI @mtop.
thanks for the reply
I may be using the wrong python version 

[jose@albiorix ~]$ which python
/usr/local/bin/python

should I shange my .bashrc file?

# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

#Original PATH
#export PATH=$PATH:$HOME/bin:$/usr/local/bin

# User specific aliases and functions
export PATH=/state/partition1/home/local/ubin/baypass_2.1/sources:/usr/local/anaconda/bin:/usr/local/bin/jre1.8.0_31/bin:/usr/local/bin:/usr/bin:$PATH:$HOME/bin:/usr/local/ubin

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
export CFLAGS="-I/usr/local/include"
export LDFLAGS="-L/usr/local/lib"

**Comment by mtop** [comment]
You can add `module load` at the end of the .bashrc file to solve this. Then run `source ~/.bashrc`.
Cheers

**Comment by jlblancopastor** [comment]
Ok, thanks !
