### ISSUE TITLE
"No module named Bio.Blast"

### ISSUE THREAD

**Issue by ismligo** [The-Bioinformatics-Group/Albiorix#97]
File "retrieve_homologues.py", line 18, in <module>
    from Bio.Blast import NCBIXML
ImportError: No module named Bio.Blast

**Comment by mtop** [comment]
@ismligo You are probably just using the wrong version of python. Use `module load` to use a different installation and try again.

**Comment by ismligo** [comment]
Yes, I have changed from 2.7.11 to 2.7.12 and it seems I don´t get the same
error any more, But I get again "ImportError: No module named Bio".

2017-06-06 19:59 GMT+02:00 Mats Töpel <notifications@github.com>:

**Comment by mtop** [comment]
Please send a bugreport (`https://github.com/The-Bioinformatics-Group/Albiorix/wiki/bugreport`) if this is still and issue.
